# For some special functionality you'll need to set some environment variables in Travis (https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings).
#
# If you want to deploy to GitHub releases (when a git-tag is built):
# - set `DEPLOY_GITHUB_RELEASES` to true
# - set `GH_TOKEN` to one of your personal access tokens from GitHub (https://help.github.com/articles/creating-an-access-token-for-command-line-use/), disable displaying the value in the build log!

fast_finish: true
os: linux
sudo: yes
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
env:
  # TODO: freexl, epsilon
  TARGET_PACKAGES="bzip2 liblzma zlib charls curl libxml2 expat libiconv libpng giflib glib tiff hdf5 libgeotiff libgta libjpeg-turbo openjpeg libwebp fontconfig freetype libspatialite proj4 sqlite3 pcre geos boost-system boost-regex boost-thread"
  CC='gcc-8' CXX='g++-8'

before_install:
  - dd if=/dev/zero of=swapfile bs=10MB count=100
  - sudo mkswap swapfile
  - sudo swapon swapfile
  - git clone https://github.com/Microsoft/vcpkg.git

install:
  - cd vcpkg
  - echo "set(CMAKE_POSITION_INDEPENDENT_CODE ON)" >> scripts/toolchains/linux.cmake
  - ./bootstrap-vcpkg.sh

script:
  - ./vcpkg install ${TARGET_PACKAGES}
  - ./vcpkg export ${TARGET_PACKAGES} --7zip

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name  "Hiroshi Miura"
  - git config --local user.email "miurahr@linux.com"
  - git tag "$(date +'%Y%m%d')-$(git log --format=%h -1)"

deploy:
  provider: releases
  file_glob: true
  api_key: "${GH_TOKEN}"
  file:
    - "vcpkg-export-*.7z"
  skip_cleanup: true
  on:
    condition: "$DEPLOY_GITHUB_RELEASES = true"
