environment:
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VSVER: 2008
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VSVER: 2010
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VSVER: 2012
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
      VSVER: 2013
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VSVER: 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VSVER: 2017

platform: 
  - x86
  - x64

matrix:
  fast_finish: true

shallow_clone: true

cache:
  - C:\tools\vcpkg\archives
  - '%LOCALAPPDATA%\pip\Cache'

init:
  - ps: |
      function exec
      {
        param ( [ScriptBlock] $ScriptBlock )
        & $ScriptBlock 2>&1 | ForEach-Object -Process { "$_" }
        if ($LastExitCode -ne 0) { exit $LastExitCode }
      }
      # set triplet and ARCHTECTURE environment valiables
      if($env:platform -eq "x86") {
        $env:VCPKG_DEFAULT_TRIPLET="x86-windows"
        $env:ARCHITECTURE="x86"}
      elseif($env:platform -eq "x64") {
        $env:VCPKG_DEFAULT_TRIPLET="x64-windows"
        $env:ARCHITCTURE="amd64"}
      else {
        $env:VCPKG_DEFAULT_TRIPLET="x86-windows"
        $env:ARCHITECTURE="x86"}
      Install-PackageProvider NuGet -Force
      Import-PackageProvider NuGet -Force
      Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
      Install-Module Pscx -AllowClobber
      Install-Module VSSetup -Scope CurrentUser
      Import-VisualStudioVars -VisualStudioVersion $env:VSVER -Architecture $env:ARCHITECTURE
      #
      cd c:\tools\vcpkg
      # refresh vcpkg repository
      exec { git pull }
      # rebuild vcpkg.exe
      .\scripts\bootstrap.ps1

install:
  - ps: |
      cd c:\tools\vcpkg
      if(Test-Path -Path archives) {
        # invalidate old cache items
        Get-ChildItem -Path archives -Include '*.zip' -Recurse | Tee-Object -Variable cachelist | Select-Object Name,LastWriteTime,CreationTime
        $cachelist | Where-Object {$_.LastWriteTime -lt (Get-Date).AddMonths(-1)} | Remove-Item
        # usable cache items
        $numpkg = Get-ChildItem -Path archives -Include '*.zip' -Recurse -Name | Measure-Object -Line | %{$_.Lines}
      } else {
        $numpkg = 0
      }
      # Here is a list of dependencies. vcpkg will build it from scratch, and
      # it take a long time to compile.
      # So we split these list into small size to keep install time under 30min.
      # We can run appveyor test 4 times, then all the dependencies will be there.
      $target1 = "bzip2","liblzma","zlib","charls","curl","libxml2","expat","libiconv","libpng","giflib","glib"
      $target2 = "freexl","tiff","hdf5","libgeotiff","libgta","libjpeg-turbo"
      $target3 = "openjpeg","libwebp","fontconfig","freetype","epsilon"
      $target4 = "libspatialite","proj4","sqlite3","pcre","geos","boost-system","boost-regex","boost-thread"
      if($numpkg -gt 20)     {$targets = $target1 + $target2 + $target3 + $target4}
      elseif($numpkg -gt 15) {$targets = $target1 + $target2 + $target3}
      elseif($numpkg -gt 10) {$targets = $target1 + $target2}
      else                   {$targets = $target1}
      exec { .\vcpkg.exe install $targets --binarycaching --keep-going }

build_script:
  - ps: |
      $commonpart="${env:VCPKG_DEFAULT_TRIPLET}-${env:VSVER}"
      $versionpart="${env:APPVEYOR_BUILD_VERSION}"
      $zipoutput="vcpkg-export-${commonpart}-${versionpart}"
      exec { .\vcpkg.exe export $targets --7zip --zip --output $zipoutput}
      move-item c:\tools\vcpkg\vcpkg-export-*.7z ${env:APPVEYOR_BUILD_FOLDER}\
      move-item c:\tools\vcpkg\vcpkg-export-*.zip ${env:APPVEYOR_BUILD_FOLDER}\
      $nugetid="vcpkg-${commonpart}"
      exec {.\vcpkg.exe export $targets --nuget --nuget-id $nugetid --nuget-version ${versionpart} }

test: off

artifacts:
  - path: '*.zip'
  - path: '*.7z'

deploy:
  - provider: BinTray
    artifact: /.*\.(zip|7z)/
    subject: osmfj
    repo: gislibs
    username: miurahr
    api_key:
      secure: VSCuTta0Npm+Rraw2LLNVyIvgAXEuSYIX+sclSKdy96Fs+dMnLGcsx+z+YDpRFeJ
    package: vcpkg-gislibs
