image:
  - Visual Studio 2017
  - Visual Studio 2015

platform: 
  - x86
  - x64

matrix:
  fast_finish: true

shallow_clone: true

cache:
  - C:\tools\vcpkg\archives
  - '%LOCALAPPDATA%\pip\Cache'

environment:
    global:
      APPVEYOR_SAVE_CACHE_ON_ERROR: true

init:
  - ps: |
      function exec
      {
        param ( [ScriptBlock] $ScriptBlock )
        & $ScriptBlock 2>&1 | ForEach-Object -Process { "$_" }
        if ($LastExitCode -ne 0) { exit $LastExitCode }
      }
      cd c:\tools\vcpkg
      # refresh vcpkg repository
      exec { git pull }
      # rebuild vcpkg.exe
      .\scripts\bootstrap.ps1
      # set triplet
      if($env:platform -eq "x86") {$env:VCPKG_DEFAULT_TRIPLET="x86-windows"}
      elseif($env:platform -eq "x64") {$env:VCPKG_DEFAULT_TRIPLET="x64-windows"}
      else {$env:VCPKG_DEFAULT_TRIPLET="x86-windows"}
      # set VSVER
      if($env:APPVEYOR_BUILD_WORKER_IMAGE -match "2015") {$env:VSVER="2015"}
      elseif($env:APPVEYOR_BUILD_WORKER_IMAGE -match "2017") {$env:VSVER="2017"}
      else {$env:VSVER="unknown"}

install:
  - ps: |
      cd c:\tools\vcpkg
      if(Test-Path -Path archives) {
        # invalidate old cache items
        Get-ChildItem -Path archives -Include '*.zip' -Recurse | Tee-Object -Variable cachelist | Select-Object Name,LastWriteTime,CreationTime
        $cachelist | Where-Object {$_.LastWriteTime -lt (Get-Date).AddMonths(-1)} | Remove-Item
        # usable cache items
        $numpkg = Get-ChildItem -Path archives -Include '*.zip' -Recurse -Name | Measure-Object -Line | %{$_.Lines}
      } else {
        $numpkg = 0
      }
      # Here is a list of dependencies. vcpkg will build it from scratch, and
      # it take a long time to compile.
      # So we split these list into small size to keep install time under 30min.
      # We can run appveyor test 4 times, then all the dependencies will be there.
      $target1 = "bzip2","liblzma","zlib","charls","curl","libxml2","expat","libiconv","libpng","giflib","glib"
      $target2 = "freexl","tiff","hdf5","libgeotiff","libgta","libjpeg-turbo"
      $target3 = "openjpeg","libwebp","fontconfig","freetype","epsilon"
      $target4 = "libspatialite","proj4","sqlite3","pcre","geos","boost-system","boost-regex","boost-thread"
      if($numpkg -gt 20)     {$targets = $target1 + $target2 + $target3 + $target4}
      elseif($numpkg -gt 15) {$targets = $target1 + $target2 + $target3}
      elseif($numpkg -gt 10) {$targets = $target1 + $target2}
      else                   {$targets = $target1}
      exec { .\vcpkg.exe install $targets --binarycaching --keep-going }
      exec { .\vcpkg.exe export $targets --7zip --nuget }

build_script:
  - ps: |
      $basename="vcpkg-export-${env:VCPKG_DEFAULT_TRIPLET}-${env:VSVER}-${env:APPVEYOR_BUILD_VERSION}"
      move-item c:\tools\vcpkg\vcpkg-export-*.7z ${env:APPVEYOR_BUILD_FOLDER}\${basename}.7z
      move-item c:\tools\vcpkg\vcpkg-export-*.nupkg ${env:APPVEYOR_BUILD_FOLDER}\${basename}.nupkg

test: off

artifacts:
  - path: '*.nupkg'
  - path: '*.7z'

deploy:
  - provider: BinTray
    artifact: /.*\.(7z)/
    subject: osmfj
    repo: gislibs
    username: miurahr
    api_key:
      secure: VSCuTta0Npm+Rraw2LLNVyIvgAXEuSYIX+sclSKdy96Fs+dMnLGcsx+z+YDpRFeJ
    package: vcpkg-gislibs
  - provider: NuGet
    artifact: /.*\.(nupkg)/
    server: https://api.bintray.com/nuget/osmfj/nuget/vcpkg-gislibs
    api_key:
      secure: hod1e3RNO3+2JRf0dX3S2qiAkdQInYqniiMDdrilyYa84rHDl0qAPc/aBUGEp1C6ike919el1fHkiD78c6+0+g==
    skip_symbols: true
