image:
  - Visual Studio 2017

platform: 
  - x86
  - x64

matrix:
  fast_finish: true

shallow_clone: true

cache:
  - C:\tools\vcpkg\archives

init:
  - ps: |
      function exec
      {
        param ( [ScriptBlock] $ScriptBlock )
        & $ScriptBlock 2>&1 | ForEach-Object -Process { "$_" }
        if ($LastExitCode -ne 0) { exit $LastExitCode }
      }
      $env:VCPKG_DIR="c:\tools\vcpkg"
      # Here is a list of dependencies. vcpkg will build it from scratch, and
      # it take a long time to compile.
      # So we split these list into small size to keep install time under 30min.
      # We can run appveyor test 4 times, then all the dependencies will be there.
      $target1 = "bzip2","liblzma","zlib","charls","curl","libxml2","expat","libiconv","libpng","giflib","glib"
      $target2 = "freexl","tiff","hdf5","libgeotiff","libgta","libjpeg-turbo" 
      $target3 = "openjpeg","libwebp","fontconfig","freetype","epsilon"
      $target4 = "libspatialite","proj4","sqlite3","pcre","geos","boost-system","boost-regex","boost-thread"
      cd $env:VCPKG_DIR
      exec { git pull }
      if(Test-Path -Path archives) {
        # invalidate old cache items
        Get-ChildItem -Path archives -Include '*.zip' -Recurse | Tee-Object -Variable cachelist
        $cachelist | Where-Object {$_.LastWriteTime -lt (Get-Date).AddMonths(-1)} | Remove-Item
        # usable cache items
        $env:numpkg = Get-ChildItem -Path archives -Include '*.zip' -Recurse -Name | Measure-Object -Line | %{$_.Lines}
      } else {
        $env:numpkg = 0
      }

install:
  - ps: |
      cd $env:VCPKG_DIR
      .\scripts\bootstrap.ps1
      if($numpkg -gt 20)     {$targets = $target1 + $target2 + $target3 + $target4}
      elseif($numpkg -gt 15) {$targets = $target1 + $target2 + $target3}
      elseif($numpkg -gt 10) {$targets = $target1 + $target2}
      else                   {$targets = $target1}
      exec { .\vcpkg.exe install $targets --binarycaching --keep-going }
      exec { .\vcpkg.exe export  $targets --7zip --nuget }

build: off

test: off

artifacts:
  - path: '*.nupkg'
  - path: '*.7z'

deploy:
  - provider: GitHub
    artifact: /.*\.(nuget|7z)/
    draft: false
    prerelease: false
    release: $(MYTARGET)-v$(appveyor_build_version)
    description: 'GIS libraries by vcpkg'
    auth_token:
      secure: m+zVt7NCf28DJqQb2v5vymIIoJ30CW/kX2zylLD7jvIxLesXajcDVvbIYPH3YnWp
    on:
      branch: master
